config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  root 'home#index'

  resources :videos, only: [:index, :show, :create, :destroy] do
    collection do
      get 'playback', to: "videos#playback"
    end
  end

  resource :user, only: [:show, :edit, :update] do
    get 'password' => 'users#password'
    collection do
      patch 'password/update' => 'users#update_password'
    end
  end

  devise_for :users, skip: [:sessions] #, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  as :user do
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    delete 'signup' => 'users/sessions#destroy', as: :destroy_user_session
  end

  get 'plans', to: 'subscriptions#plans'
  post 'subscription_checkout', to: 'subscriptions#subscription_checkout'
end

app/models/video.rb
class Video < ActiveRecord::Base
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

  validates :link, presence: true, uniqueness: true, format: YT_LINK_FORMAT, length: { maximum: 43, message: "is invalid" }

  default_scope { order(created_at: :desc) }

  before_create :set_attributes

  def set_attributes
  	video = Yt::Video.new url: self.link
  	self.yt_id = video.id
  	self.title = video.title
    self.thumbnail_url = video.thumbnail_url(:medium)
  	self.channel_title = video.channel_title
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :destroy]
  before_action :set_videos, only: [:index, :show, :create]
  before_action :set_playback_videos, only: [:playback]
  before_action :set_loader_path, only: [:index]
  before_action :authenticate_user!, only: [:destroy]

  rescue_from Yt::Errors::ServerError do |exception|
    redirect_to videos_url, alert: "Unable to connect to YouTube"
  end

  # GET /videos
  # GET /videos.json
  def index
    @video = Video.new
  end

  def show    
  end
  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    if cookies[:request_count].to_i < 3 or user_signed_in?
      respond_to do |format|
        if @video.save
          cookies[:request_count] = { value: cookies[:request_count].to_i + 1, expires: 6.hour.from_now }
          format.html { redirect_to videos_url, notice: 'Video was added.' }
        else
          format.html { render :index }
        end
      end
    else
      redirect_to videos_url, alert: 'Ups! Sorry.. Your allowed request only 3 times.'
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    status = true #@video.destroy
    render json: { success: status }
    # redirect_to videos_url, notice: "<strong>#{@video.title}</strong>".html_safe + ' was removed.'
  end

  def playback
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find_by!(yt_id: params[:id])
    end

    def set_videos
      @videos = Video.all.page(params[:page]).per(9)
      @videos_size = Video.all.size
    end

    def set_playback_videos
      @videos = Video.all
      @videos_size = @videos.size
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:link)
    end

    def set_loader_path
      gon.ajax_loader_path = ActionController::Base.helpers.image_path("loading.gif")
    end
end

app/helpers/videos_helper.rb
module VideosHelper
	def embed_video(youtube_id, options={})
		autoplay = options[:autoplay] ? 1 : 0;
    content_tag(:iframe, nil, 
    	src: "//www.youtube.com/embed/#{youtube_id}?version=3&enablejsapi=1&autoplay=#{autoplay};wmode=opaque",
    	frameborder: 0, 
    	id: "video-player",
    	data: {
    		video: youtube_id
    	}
    )
  end
end

app/views/videos/_videos.html.slim
- isAdmin = current_user.has_role?("admin") if user_signed_in?

.list-group
	- @videos.each do |video|
		= link_to video_path(video.yt_id), remote: true, class: "video video-link list-group-item"
			.video-box
				.col-md-4.col-sm-4.col-xs-12
					= image_tag video.thumbnail_url, alt: video.title, class: "img-responsive"
				.col-md-8.col-sm-8.col-xs-12
					h4 = video.title
					.text-muted = video.channel_title

			- if isAdmin
				button class="video-remove" data-video="#{video.yt_id}" data-toggle="tooltip" data-container="body" title="Remove from playlist" class="btn btn-default btn-sm"
					span.glyphicon.glyphicon-remove

app/views/videos/index.html.slim
- if @video.errors.any?
  .alert.alert-danger role="alert"
    a.close aria-label="close" data-dismiss="alert" href="#"  &times;
    - @video.errors.full_messages.each do |message|
      li = message

= form_for @video, html: { class: "form-horizontal" } do |f|
  .input-group
    = f.text_field :link, class: 'text_field form-control', placeholder: "enter youtube link to added: e.g https://www.youtube.com/watch?v=hrfik3U2U0A"
    span.input-group-btn
      = f.submit "Add Video", class: 'btn btn-default'
  span.help-block.text-right = "Please <strong>do not</strong> add inappropriate content.".html_safe

.videos  
  - if @videos.present?
    .row
      .col-md-12
        .embed-container
          = embed_video(@videos.first.yt_id)

  h4.page-header
    | Videos (#{@videos_size})

  .infinite-scroll
    = render partial: 'videos', object: @videos

  .pagination
    = link_to_next_page(@videos, '', remote: true)

- content_for :js_tag
  = javascript_include_tag "https://www.youtube.com/iframe_api"
  = javascript_include_tag "videos"
  = javascript_include_tag "infinite-scroll"

app/views/videos/index.js.erb
// Append new data
$("<%=j render partial: 'videos', object: @videos %>").appendTo($(".infinite-scroll"));

// Update pagination link
<% if @videos.last_page? %>
  $('.pagination').html("That's all, folks!");
<% else %>
  $('.pagination')
    .html("<%=j link_to_next_page(@videos, 'Next Page', remote: true) %>");
<% end %>

app/views/videos/playback.html.slim
- content_for :js_tag
  = javascript_include_tag "http://www.youtube.com/player_api", 'data-turbolinks-track' => true
  = javascript_include_tag "videos", 'data-turbolinks-track' => true
  = javascript_include_tag "infinite-scroll", 'data-turbolinks-track' => true

.videos
  h2.page-header
    | Videos (#{@videos_size})

  - @videos.each do |video|
    = react_component('Video',
      thumbnailUrl: video.thumbnail_url,
      title: video.title,
      linkYt: link_to_yt(video.yt_id),
      channelTitle: video.channel_title,
      userSignedIn: user_signed_in?,
      isAdmin: user_signed_in? ? current_user.has_role?("admin") : false,
      videoPath: video_path(video))

app/views/videos/show.js.erb
change();
$('#video-player').attr('data-setup', "{ \"techOrder\": [\"youtube\"], \"sources\": [{ \"type\": \"video/youtube\", \"src\": \"<%= @video.link %>\"}], \"youtube\": { \"playlist\": \"<%= @videos.pluck(:yt_id).join(',')%>\", \"ytControls\": 2 } }");

video.src({"type":"video/youtube", "src":"<%= @video.link %>"});
video.play();
video.on('ended', function(){	
});