config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  root 'home#index'

  resources :videos, only: [:index, :show, :create, :destroy] do
    collection do
      get 'playback', to: "videos#playback"
    end
  end

  resource :user, only: [:show, :edit, :update] do
    get 'password' => 'users#password'
    collection do
      patch 'password/update' => 'users#update_password'
    end
  end

  devise_for :users, skip: [:sessions] #, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  as :user do
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    delete 'signup' => 'users/sessions#destroy', as: :destroy_user_session
  end

  get 'plans', to: 'subscriptions#plans'
  post 'subscription_checkout', to: 'subscriptions#subscription_checkout'
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :videos

  validates :name, :privacy, presence: true
  validates :name, length: { maximum: 30 }

  scope :current_user, -> { where(user_id: User.current.id) }
  scope :privacy_public, -> { where(privacy: "public") }
  scope :privacy_private, -> { where(privacy: "private") }
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = if user_signed_in? 
      Playlist.current_user
    else
      Playlist.privacy_public
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @video = @playlist.videos.new
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user_id = current_user.id

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: "Playlist #{@playlist.name} was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to request.referer, notice: 'Playlist was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name, :privacy)
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
	def playlist_info(playlist)
		content_tag :span,
		"by #{playlist.user.email} &bull; #{pluralize(playlist.videos.size-1, 'video')} &bull; #{playlist.privacy.titleize}".html_safe,
		class: "small text-muted"
	end
end

app/views/playlists/_form.html.slim
= form_for @playlist do |f|
  - if @playlist.errors.any?
    .alert.alert-danger role="alert"
      a.close aria-label="close" data-dismiss="alert" href="#"  &times;
      - @playlist.errors.full_messages.each do |message|
        li = message

  .form-group.required
    = f.label :name, class: "label-control required"
    = f.text_field :name, class: "form-control"

  .form-group.required
    = f.label :privacy, class: "label-control required"
    label.radio-inline
      = f.radio_button :privacy, "public"
      | Public
    label.radio-inline
      = f.radio_button :privacy, "private"
      | Private

  .form-group
    = f.submit class: "btn btn-primary"

app/views/playlists/edit.html.slim
h1 Editing playlist

== render 'form'

= link_to 'Show', @playlist
'|
= link_to 'Back', playlists_path

app/views/playlists/index.html.slim
- content_for :css_tag
  = stylesheet_link_tag "playlists", :media => "all"

.btn-new-playlist.pull-right 
  = link_to 'New Playlist', new_playlist_path, class: "btn btn-default"

h1 Playlists

hr

.playlists
  - @playlists.each do |playlist|
    .row
      .col-md-8.col-sm-8.col-xs-12
        h4 
          strong = link_to playlist.name, playlist
        = playlist_info(playlist)
      .btn-action-playlist.col-md-4.col-sm-4.col-xs-12
        = link_to 'Edit', edit_playlist_path(playlist), class: "btn btn-sm btn-info"
        '
        = link_to 'Remove', playlist, data: {:confirm => 'Are you sure?'}, :method => :delete, class: "btn btn-sm btn-danger"

app/views/playlists/new.html.slim
h1 New playlist

== render 'form'

= link_to 'Back', playlists_path

app/views/playlists/show.html.slim
h4.page-header
	strong = @playlist.name
= playlist_info(@playlist)

- if @video.errors.any?
  .alert.alert-danger role="alert"
    a.close aria-label="close" data-dismiss="alert" href="#"  &times;
    - @video.errors.full_messages.each do |message|
      li = message

= form_for @video, html: { class: "form-horizontal" } do |f|
  .input-group
    = f.text_field :link, class: 'text_field form-control', placeholder: "enter youtube link to added: e.g https://www.youtube.com/watch?v=hrfik3U2U0A"
    span.input-group-btn
      = f.submit "Add Video", class: 'btn btn-default'
  span.help-block.text-right = "Please <strong>do not</strong> add inappropriate content.".html_safe