config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  root 'home#index'

  resources :videos, only: [:index, :show, :create, :destroy] do
    collection do
      get 'playback', to: "videos#playback"
    end
  end

  resource :user, only: [:show, :edit, :update] do
    get 'password' => 'users#password'
    collection do
      patch 'password/update' => 'users#update_password'
    end
  end

  devise_for :users, skip: [:sessions] #, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  as :user do
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    delete 'signup' => 'users/sessions#destroy', as: :destroy_user_session
  end

  get 'plans', to: 'subscriptions#plans'
  post 'subscription_checkout', to: 'subscriptions#subscription_checkout'
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
	head
		meta charset="utf-8"
		meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
		= viewport_meta_tag
		title= content_for?(:title) ? yield(:title) : "Playt"
		= csrf_meta_tags

		/! Le HTML5 shim, for IE6-8 support of HTML elements
		/[if lt IE 9]
			= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
			= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js"
		= stylesheet_link_tag "application", :media => "all"
		= yield :css_tag
		= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
		= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
		= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
		= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
		= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
		= Gon::Base.render_data		

	BODY
		.container
			.header.clearfix
				nav
					ul.nav.nav-pills.pull-right
						li class="#{active_class(root_path)}" role="presentation" = link_to "Home", root_path
						li class="#{active_class(videos_path)}" role="presentation" = link_to "Videos", videos_path											
						
						- if user_signed_in?			
							li class="#{active_class(playlists_path)}" role="presentation" = link_to "Playlists", playlists_path				
							li class="#{active_class(playback_videos_path)}" role="presentation" = link_to "Playback", playback_videos_path
							li class="#{active_class(plans_path)}" role="presentation" = link_to "Plans", plans_path
							li.dropdown
							  a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
							    = current_user.email
							    span.caret
							  ul.dropdown-menu
							    li = link_to "Account", user_path
							    li = link_to "Change Password", password_user_path
							    li = link_to "Logout", destroy_user_session_path, method: :delete

				h3.text-muted
					= image_tag "logo.png", alt: "Playt", class: "img-brand"
					.brand Playt

			= bootstrap_flash
			= yield

			a.btn.btn-info.scrollup href="#"
			  span.glyphicon.glyphicon-chevron-up

			footer.footer
				p = link_to image_tag('GitHub-Mark-32px.png'), "https://github.com/avidmaulanas/playt", target: "_blank", title: "Source on GitHub", data: {toggle: "tooltip", placement: "right"}

		= javascript_include_tag "application"
		= yield :js_tag